### ISSUE TITLE
Dinner Club: Add restrictions to price field

### ISSUE THREAD

**Issue by thygesteffensen** [nymann/Accountant#11]
Program cannot currently handle text input, error code 500...

**Comment by nymann** [comment]
Seems reasonable :+1:

**Comment by thygesteffensen** [comment]
For now, input type is changed to number from text, however this will only work on newer browsers and not on mobile devices...

**Comment by thygesteffensen** [comment]
Inputbox will only accept numbers or 'e'. Non-numbers will be caught within HTML. Non-numbers and 'e' will be caught in backend, as well as negative numbers and numbers above 2000.
