### ISSUE TITLE
Dinner Club: Remove attendant from predefined list of active dinner club members.

### ISSUE THREAD

**Issue by thygesteffensen** [nymann/Accountant#13]
Make it possible to remove (deselect) active dinner club members from a meal.
Perhaps using check boxes in drop down or make the background highlighted.

**Comment by thygesteffensen** [comment]
Perhaps one should not have the ability to add or remove an attendant. An attandant should chose actively to pass to that  meal or bring a/several guest(s).

**Comment by nymann** [comment]
@thygesteffensen I'm not sure if I follow.

A dinner entry should be editable, and I think a user should be able to have the following options:
* If the user was mistakenly added as a participant, he or she should be able to say "I didn't take part of this dinner club meal" (Open dispute)
* Or on the other hand if the person who registered the dinner forgot to add a person, that person should be able to, add himself/herself: "I took part"

And like wise for guests, I presume.

**Comment by thygesteffensen** [comment]
Yes, the user should have that ability.
Okay, so let's say we have one fixed food club, once a week, let's say monday. Then, by default, all active users are marked to attend. Right? If a user cannot attend, he/she should actively take action and pass.
However, I think we are discussing to different approaches or I'm mistaken. 
-- Let's take it tonight
