### ISSUE TITLE
API: Flask-RESTPlus

### ISSUE THREAD

**Issue by nymann** [nymann/Accountant#14]
Look into Flask RESTPlus, we would benefit from an API to do tasks such as deleting or updating dinner-club meals.

**Comment by thygesteffensen** [comment]
Could this be out solution for the accounting problem.
If we make API for all DB interaction, then we could manage every users balance.
Let's say, when we create a dinner club meal. Then we use the API to insert the dinner into the DB, when we do that, the API method calculates how every attendants balance should be updated.
Then there is no need for us, to calculate the balance every time, we simple do that, every time we insert into the DB.

**Comment by thygesteffensen** [comment]
RESTPlus er implementeret, dog skal der findes en måde hvorpå vi kan bekræfte en bruger
