### ISSUE TITLE
Display needed items.

### ISSUE THREAD

**Issue by nymann** [nymann/Accountant#44]
We need a list that displays the needed items ("items to buy").

**Comment by thygesteffensen** [comment]
Needed items will be showed on the index site and added with a modal.
It should be possible, when adding an entry, to select one of the needed items, which the should be removed from the list.

**Comment by thygesteffensen** [comment]
[https://github.com/nymann/Accountant/commit/0f9916aed36fcd75507ecf4c3f0516b563e1c1b5](https://github.com/nymann/Accountant/commit/0f9916aed36fcd75507ecf4c3f0516b563e1c1b5)
The function has NOT been added, but it will in the near future
